const Bank = [
   {
      key: "1",
      num: "1.",
      name: "Bank KCP Soreang",
      address: "Jl. Soreang 181 Bandung",
      lda: "Lihat Details",
   },
   {
      key: "2",
      num: "2.",
      name: "Bank KCP Banjaran",
      address: "Jl. Banjaran 182 Bandung",
      lda: "Lihat Details",
   },
   {
      key: "3",
      num: "3.",
      name: "Bank KCP Kamasan",
      address: "Jl. Kamasan 184 Bandung",
      lda: "Lihat Details",
   },
   {
      key: "4",
      num: "4.",
      name: "Bank KCP Waru",
      address: "Jl. Waru 190 Bandung",
      lda: "Lihat Details",
   },
   {
      key: "5",
      num: "5.",
      name: "Bank KCP Eoreang",
      address: "Jl. Eoreang 185 Bandung",
      lda: "Lihat Details",
   },
   {
      key: "6.",
      num: "6.",
      name: "Bank KCP Foreang",
      address: "Jl. Foreang 186 Bandung",
      lda: "Lihat Details",
   },
   {
      key: "7",
      num: "7.",
      name: "Bank KCP Goreang",
      address: "Jl. Goreang 187 Bandung",
      lda: "Lihat Details",
   },
   {
      key: "8",
      num: "8.",
      name: "Bank KCP Horeang",
      address: "Jl. Horeang 188 Bandung",
      lda: "Lihat Details",
   },
   {
      key: "9",
      num: "9.",
      name: "Bank KCP Ioreang",
      address: "Jl. Ioreang 189 Bandung",
      lda: "Lihat Details",
   },
   {
      key: "10.",
      num: "10.",
      name: "Bank KCP Joreang",
      address: "Jl. Joreang 190 Bandung",
      lda: "Lihat Details",
   },
   {
      key: "11",
      num: "11.",
      name: "Bank KCP Koreang",
      address: "Jl. Koreang 191 Bandung",
      lda: "Lihat Details",
   },
   {
      key: "12",
      num: "12.",
      name: "Bank KCP Loreang",
      address: "Jl. Loreang 192 Bandung",
      lda: "Lihat Details",
   },
   {
      key: "13",
      num: "13.",
      name: "Bank KCP Moreang",
      address: "Jl. Moreang 193 Bandung",
      lda: "Lihat Details",
   },
   {
      key: "14",
      num: "14.",
      name: "Bank KCP Noreang",
      address: "Jl. Noreang 194 Bandung",
      lda: "Lihat Details",
   },
   {
      key: "15",
      num: "15.",
      name: "Bank KCP Toreang",
      address: "Jl. Toreang 196 Bandung",
      lda: "Lihat Details",
   },
];

export default Bank;
